# Generated by Django 5.1 on 2024-09-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRolSong',
            fields=[
                ('artist_rol_song_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongApp.artist')),
                ('fk_song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongApp.song')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ArtistRol',
        ),
        migrations.AddField(
            model_name='artistrolsong',
            name='fk_rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SongApp.rol'),
        ),
    ]
