# Generated by Django 5.1 on 2024-09-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongApp', '0003_song_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_lyrics_e',
            field=models.CharField(default='docktorspile', max_length=100),
            preserve_default=False,
        ),
    ]
