# Generated by Django 5.1 on 2024-09-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SongApp', '0005_alter_song_song_lyrics_e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='fk_almbum_id',
            new_name='fk_album_id',
        ),
    ]
